spring:
  config:
    import: optional:file:src/main/resources/application-secret.env[.properties]
  application:
    name: NaengpaMasterBackend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/naengpa_master}
    driver-class-name: ${DB_DRIVER_CLASS_NAME:org.postgresql.Driver}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    open-in-view: ${JPA_OPEN_IN_VIEW:false}
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:}
  expiration: ${JWT_EXPIRATION:3600000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:1209600000}
